### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by levin-kelevra** [frosas/spotify-to-mp3#54]
```
/var/lib/gems/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:445:in `rescue in transmit': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (RestClient::SSLCertificateNotVerified)
	from /var/lib/gems/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:350:in `transmit'
	from /var/lib/gems/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:176:in `execute'
	from /var/lib/gems/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:41:in `execute'
	from /var/lib/gems/2.1.0/gems/rest-client-1.7.2/lib/restclient/abstract_response.rb:82:in `follow_redirection'
	from /var/lib/gems/2.1.0/gems/rest-client-1.7.2/lib/restclient/abstract_response.rb:41:in `return!'
	from /var/lib/gems/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:495:in `process_result'
	from /var/lib/gems/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:421:in `block in transmit'
	from /usr/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /var/lib/gems/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:413:in `transmit'
	from /var/lib/gems/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:176:in `execute'
	from /var/lib/gems/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:41:in `execute'
	from /var/lib/gems/2.1.0/gems/rest-client-1.7.2/lib/restclient.rb:65:in `get'
	from /var/lib/gems/2.1.0/gems/grooveshark-0.2.14/lib/grooveshark/client.rb:120:in `token_data'
	from /var/lib/gems/2.1.0/gems/grooveshark-0.2.14/lib/grooveshark/client.rb:11:in `initialize'
	from /home/slevinkelevra/soft/github.com/spotify-to-mp3/lib/spotify_to_mp3/dependency_container.rb:15:in `new'
	from /home/slevinkelevra/soft/github.com/spotify-to-mp3/lib/spotify_to_mp3/dependency_container.rb:15:in `grooveshark'
	from /home/slevinkelevra/soft/github.com/spotify-to-mp3/lib/spotify_to_mp3/dependency_container.rb:23:in `app'
	from /home/slevinkelevra/soft/github.com/spotify-to-mp3/bin/spotify-to-mp3:7:in `<top (required)>'
	from /var/lib/gems/2.1.0/bin/spotify-to-mp3:23:in `load'
	from /var/lib/gems/2.1.0/bin/spotify-to-mp3:23:in `<main>'
```

**Comment by DysLabs** [comment]
"Grooveshark, the service this app was relying on, has shut down. Don't expect it to work anymore :("
