### ISSUE TITLE
certificate verify failed (RestClient::SSLCertificateNotVerified)

### ISSUE THREAD

**Issue by bolorkhuu** [frosas/spotify-to-mp3#55]
i've tried to check out this, unfortunately it does not work. 

```
23:30:43
> spotify-to-mp3 songs.txt 
/usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:445:in `rescue in transmit': SSL_connect returned=1 errno=0 state=error: certificate verify failed (RestClient::SSLCertificateNotVerified)
	from /usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:350:in `transmit'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:111:in `follow_redirection'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:67:in `return!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
	from /usr/local/lib/ruby/gems/2.2.0/gems/grooveshark-0.2.14/lib/grooveshark/client.rb:120:in `token_data'
	from /usr/local/lib/ruby/gems/2.2.0/gems/grooveshark-0.2.14/lib/grooveshark/client.rb:11:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spotify-to-mp3-0.7.2/lib/spotify_to_mp3/dependency_container.rb:15:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spotify-to-mp3-0.7.2/lib/spotify_to_mp3/dependency_container.rb:15:in `grooveshark'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spotify-to-mp3-0.7.2/lib/spotify_to_mp3/dependency_container.rb:23:in `app'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spotify-to-mp3-0.7.2/bin/spotify-to-mp3:7:in `<top (required)>'
	from /usr/local/bin/spotify-to-mp3:23:in `load'
	from /usr/local/bin/spotify-to-mp3:23:in `<main>'
```

does anyone know how to solve this issue?
thanks!

**Comment by annettaws** [comment]
I have the same problem. Have you solve it?
Thanks!
